### ISSUE TITLE
Ugly scrolls bars on Windows version of Chrome

### ISSUE THREAD

**Issue by jcollard** [LearnCodeOrg/codetrain#2]
On the `Docs` page, there are visible scrollbars that show up making the page a little ugly. Nothing disfunctional, just ugly.

![2021-12-03 13_57_59-Window](https://user-images.githubusercontent.com/3529380/144678309-6a6f6f8c-33d6-4da8-8b0e-c9f4bf35593c.png)

**Comment by csaye** [comment]
Thanks for letting me know! I'll fix this right away.

**Comment by csaye** [comment]
Should be resolved with 6f7619536137486ddca3c2d16ee1b7f61b021eb4.
