### ISSUE TITLE
Feature Request: Remix own project / Save As / Create Version

### ISSUE THREAD

**Issue by jcollard** [LearnCodeOrg/codetrain#6]
Currently, a creator cannot remix their own project.

It would be nice to have an option to either `Remix` a current project, `Save As` a different project name, or to create tags for a specific `Version`. This would be useful for backing up projects just in case you accidentally make a super breaking change.

Just a thought! I personally like the `Version` option the most but I don't think new programmers would understand what that term means.

**Comment by csaye** [comment]
Thanks for the suggestion, this makes total sense. I'll get to work on a way to remix your own project.

**Comment by csaye** [comment]
Resolved with a57cddb0881c42ef58ed97aee824ae91c1834efe.
