### ISSUE TITLE
Feature Request: Allow `Key Values` for user Input

### ISSUE THREAD

**Issue by jcollard** [LearnCodeOrg/codetrain#7]
As far as I can tell, there is not a simple way to use `isKey` and `isKeyDown` with the arrow keys / escape key / special keys.

It would be great to have support for the `Key Values` specified here: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key/Key_Values

**Comment by csaye** [comment]
Thanks for pointing this out — I'll get to work on it.

**Comment by csaye** [comment]
Resolved with 9dcc158692a323a95ef0493d304d06963cd5b239.
