### ISSUE TITLE
Bug: Display transparent pixels on `Explore` screen

### ISSUE THREAD

**Issue by jcollard** [LearnCodeOrg/codetrain#8]
The preview icon on the `Explore` screen doesn't display transparent pixels properly.

Here is a screenshot of what it currently looks like in Chrome on Mac:

<img width="165" alt="Screen Shot 2021-12-04 at 4 13 51 AM" src="https://user-images.githubusercontent.com/3529380/144709027-40f46993-db18-4357-979d-e42d19150cb6.png">

**Comment by csaye** [comment]
Thanks for letting me know. Fixed with 27a5432c16bad8cc6777092019d7c7f11012b7ac.
